Fixes Issue #185 (#186)
* Fixes Issue #185

Have a look to https://github.com/Keyang/node-csvtojson/issues/185 for explanation

* Uses var instead of let for compatibility

* Changes Buffer.allocUnsafe to Buffer.alloc

Even though it Buffer.allocUnsafe is documented in Node, I'm getting this error in some Node versions:

```
2) CSV Converter should emit data event correctly:
     Uncaught TypeError: Buffer.allocUnsafe is not a function
```

* Adds support for very old Node.js versions